name: CubeAssemble
main: com.dorianmercier.cubeassemble.common.main
version: 2.0
api-version: 1.17

commands:
   init:
      description: Command to initialize the game.
      usage: /<command>
      permission: op
      permission-message: You don't have <permission>
   clean:
      description: Command to clean the game.
      usage: /<command>
      permission: op
      permission-message: You don't have <permission>