name: CubeAssemble
main: com.dorianmercier.cubeassemble.common.main
version: 2.0
api-version: 1.17

commands:
   init:
      description: CubeAssemble command to initialize the game.
      usage: /<command>
      permission: op
      permission-message: You don't have <permission>
   clean:
      description: CubeAssemble command to clean the game.
      usage: /<command>
      permission: op
      permission-message: You don't have <permission>
   setup:
       description: CubeAssemble command to get setup mode
       usage: /<command>
       permission: op
       permission-message: You don't have <permission>
   test:
       description: CubeAssemble test command
       usage: /<command>
       permission: op
       permission-message: You don't have <permission>
     