name: CubeAssemble
main: com.dorianmercier.cubeassemble.main
version: 2.0

name: Basic
main: com.dorianmercier.cubeassemble.common.main
version: 1.0
author: <your IGN or name>
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>